AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 250

Metrics/AbcSize:
  Max: 45

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15 